services:
  # üê∂ Backend NestJS
  backend:
    build:
      context: .
    container_name: peluditos_back
    ports:
      - "127.0.0.1:8080:8080"   # Ahora solo accesible desde el VPS
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root2024
      - MYSQL_DB=peluditos
      - WHATSAPP_API_TOKEN=EAAPm6sQ5Qp8BPk4IbihTvpg1nOdB9AKwyzUAGq0Lebc4IolbIcow0iwNe2N21VHTps5kPyDnUaNAxtPTXxKNuBhTRcbtBL1nqa2uDyKYKHqT9GDkSb5TF81ZAfWZCnYLtp1J5ssm98WDngZCIcgczrXq8UMMrxuoLpRmTlIftkVskcd5ZAwBXKyXZCzI7KyS6XgZDZD
    depends_on:
      - mysql
    networks:
      - pelunet

  # üåê Frontend Next.js
  frontend:
    build:
      context: ../peluditos_front
    container_name: peluditos_front
    ports:
      - "127.0.0.1:3000:3000"   # SOLO nginx accede
    depends_on:
      - backend
    networks:
      - pelunet

  # üóÑÔ∏è Base de datos MySQL
  mysql:
    image: mysql:8
    container_name: peluditos_mysql
    restart: always
    ports:
      - "127.0.0.1:3316:3306"   # SOLO accesible desde localhost
    environment:
      - MYSQL_ROOT_PASSWORD=root2024
      - MYSQL_DATABASE=peluditos
    volumes:
      - mysql-data:/var/lib/mysql
      - ./sql/datos_iniciales.sql:/docker-entrypoint-initdb.d/datos_iniciales.sql
    networks:
      - pelunet

volumes:
  mysql-data:

networks:
  pelunet:
    driver: bridge
